### ISSUE TITLE
Environmental installation encountered issues when running //monolith/native_training:demo

### ISSUE THREAD

**Issue by ZoeyChen-lab** [bytedance/monolith#7]
I run "bazel run //monolith/native_training:demo --output_filter=IGNORE_LOGS", then occur the following error.
Someone can help answer the question？Thanks~

error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/cy/opt/anaconda3/envs/python310/include -fPIC -O2 -isystem /Users/cy/opt/anaconda3/envs/python310/include -g0 -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=3 -DHAVE_CBLAS -Ibuild/src.macosx-10.9-x86_64-3.10/numpy/core/src/umath -Ibuild/src.macosx-10.9-x86_64-3.10/numpy/core/src/npymath -Ibuild/src.macosx-10.9-x86_64-3.10/numpy/core/src/common -Inumpy/core/include -Ibuild/src.macosx-10.9-x86_64-3.10/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/cy/PycharmProjects/chatGLM/tensorflow/monolith/my-test-env/include -I/Users/cy/opt/anaconda3/envs/python310/include/python3.10 -Ibuild/src.macosx-10.9-x86_64-3.10/numpy/core/src/common -Ibuild/src.macosx-10.9-x86_64-3.10/numpy/core/src/npymath -c build/src.macosx-10.9-x86_64-3.10/numpy/core/src/multiarray/scalartypes.c -o build/temp.macosx-10.9-x86_64-3.10/build/src.macosx-10.9-x86_64-3.10/numpy/core/src/multiarray/scalartypes.o -MMD -MF build/temp.macosx-10.9-x86_64-3.10/build/src.macosx-10.9-x86_64-3.10/numpy/core/src/multiarray/scalartypes.o.d -msse3 -I/System/Library/Frameworks/vecLib.framework/Headers" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for numpy
  ERROR: Command errored out with exit status 1:
   command: /Users/cy/PycharmProjects/chatGLM/tensorflow/monolith/my-test-env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dk/p__18bnx7c96lgzrbn7fjh2h0000gn/T/pip-wheel-8gof1mee/numpy/setup.py'"'"'; __file__='"'"'/private/var/folders/dk/p__18bnx7c96lgzrbn7fjh2h0000gn/T/pip-wheel-8gof1mee/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/dk/p__18bnx7c96lgzrbn7fjh2h0000gn/T/pip-wheel-8gof1mee/numpy

ERROR: Failed cleaning build dir for numpy
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "/Users/cy/opt/anaconda3/envs/python310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/cy/opt/anaconda3/envs/python310/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/private/var/tmp/_bazel_cy/7227b87b59980dee872adc59136222e4/external/rules_python/python/pip_install/extract_wheels/__main__.py", line 5, in <module>
    main()
  File "/private/var/tmp/_bazel_cy/7227b87b59980dee872adc59136222e4/external/rules_python/python/pip_install/extract_wheels/__init__.py", line 87, in main
    subprocess.run(pip_args, check=True)
  File "/Users/cy/opt/anaconda3/envs/python310/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/cy/PycharmProjects/chatGLM/tensorflow/monolith/my-test-env/bin/python3', '-m', 'pip', 'wheel', '-r', '/Users/cy/PycharmProjects/chatGLM/tensorflow/monolith/third_party/pip_deps/requirements.txt']' returned non-zero exit status 1.
)
INFO: Elapsed time: 158.542s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by zlqiszlqbd** [comment]
When we build this, python 3.10 is not published yet. So you can try 3.7/3.8, once we updated tensorflow version it shall work.
